apiVersion: v1
kind: BastionNetworkPolicy
metadata:
  name: ubuntu-1-to-fqdn
  microservice_name: multiubuntu
spec:
  selector:
    matchLabels:
      container: ubuntu-1
  egress:
    toFQDNs:
    - name: remote.0x010.com
    # allow image.0x010.com (for FQDN test)
  action:
    drop
