apiVersion: v1
kind: BastionNetworkPolicy
metadata:
  name: ubuntu-1-to-fqdn
  microservice_name: multiubuntu
spec:
  selector:
    matchLabels:
      container: ubuntu-1
  egress:
    toFQDNs:
    - name: remote.zerosec.info
    # allow image.zerosec.info (for FQDN test)
  action:
    drop
