apiVersion: v1
kind: BastionNetworkPolicy
metadata:
  name: ubuntu-4-to-ubuntu-5-http
  microservice_name: multiubuntu
spec:
  selector:
    matchLabels:
      container: ubuntu-4
  egress:
    matchLabels:
      container: ubuntu-5
    toPorts:
    - protocol: http
      ports: "8000"
    toHTTPs:
    - method: GET
      path: /
    - method: GET
      path: /test1
    # block [GET] /teset2
  action:
    pass
