apiVersion: v1
kind: BastionNetworkPolicy
metadata:
  name: group-1-to-cidr
  microservice_name: multiubuntu
spec:
  selector:
    matchLabels:
      group: group-1
  egress:
    toCIDRs:
    - cidr: 143.248.38.0/24 # block 143.248.38.18 (sdx4u.net) and 143.248.38.95 (neticraft.com)
      except:
      - 143.248.38.44/32 # (image.0x010.com for FQDN test)
      - 143.248.38.47/32 # allow (clair.0x010.com)
  action:
    drop
