apiVersion: v1
kind: BastionNetworkPolicy
metadata:
  name: group-1-to-cidr
  microservice_name: multiubuntu
spec:
  selector:
    matchLabels:
      group: group-1
  egress:
    toCIDRs:
    - cidr: 143.248.38.0/24 # block 143.248.38.51 (sdxdata.com) and 143.248.38.95 (neticraft.com)
      except:
      - 143.248.38.18/32 # allow (sdx4u.net)
      - 143.248.38.44/32 # (image.zerosec.info for FQDN test)
  action:
    drop
