apiVersion: v1
kind: BastionNetworkPolicy
metadata:
  name: group-1-to-cidr
  microservice_name: multiubuntu
spec:
  selector:
    matchLabels:
      group: group-1
  egress:
    toCIDRs:
    - cidr: 143.248.38.0/24 # test 143.248.38.51 and 143.248.38.95
      except:
      - 143.248.38.18/32
      - 143.248.38.112/32
  action:
    drop
