apiVersion: v1
kind: BastionRuntimePolicy
metadata:
  name: group-2-to-secret
  microservice_name: multiubuntu
spec:
  selector:
    matchLabels:
      group: group-2
  file:
    matchDirectories:
    - /secret
  action:
    enforce
