apiVersion: v1
kind: BastionSystemPolicy
metadata:
  name: group-1-w-curl
  microservice_name: multiubuntu
spec:
  selector:
    matchLabels:
      group: group-1
  process:
    matchNames:
    - curl
  action:
    drop
